services:

  nats-server:
    image: nats:latest

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: 586250440358.dkr.ecr.us-east-1.amazonaws.com/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  products-microservice:
    build: 
      context: ./products-microservice
      dockerfile: dockerfile.prod
    image: 586250440358.dkr.ecr.us-east-1.amazonaws.com/products-microservice
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

#   orders-db:
#     image: postgres:16.2
#     volumes:
#       - ./orders-microservice/postgres:/var/lib/postgresql/data
#     ports:
#       - 5432:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: ordersdb

  orders-microservice:
    build: 
      context: ./orders-microservice
      dockerfile: dockerfile.prod
      args:
        ORDERS_MICROSERVICE_DATABASE: ${ORDERS_MICROSERVICE_DATABASE}
    image: 586250440358.dkr.ecr.us-east-1.amazonaws.com/orders-microservice
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_MICROSERVICE_DATABASE}

  
  auth-microservice:
    build: 
      context: ./auth-microservice
      dockerfile: dockerfile.prod
    image: 586250440358.dkr.ecr.us-east-1.amazonaws.com/auth-microservice
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

# # =================================================================================================
# # Payments Microservice
# # =================================================================================================
  payments-microservice:
    build:
      context: ./payments-microservice
      dockerfile: dockerfile.prod
    image: 586250440358.dkr.ecr.us-east-1.amazonaws.com/payments-microservice
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=${PAYMENTS_MICROSERVICE_PORT}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}