apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders-microservice
  name: orders-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-microservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-microservice
    spec:
      containers:
      - image: 586250440358.dkr.ecr.us-east-1.amazonaws.com/orders-microservice
        name: orders-microservice
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: orders-secrets
              key: database_url
        resources: {}
status: {}
