apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: orders-microservice
  name: orders-microservice
spec:
  ports:
  - name: "3002"
    port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: orders-microservice
  type: ClusterIP
status:
  loadBalancer: {}
