apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products-microservice
  name: products-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-microservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-microservice
    spec:
      containers:
      - image: 586250440358.dkr.ecr.us-east-1.amazonaws.com/products-microservice
        name: products-microservice
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          value: "file:./dev.db"
        resources: {}
status: {}
