apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: products-microservice
  name: products-microservice
spec:
  ports:
  - name: "3001"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: products-microservice
  type: ClusterIP
status:
  loadBalancer: {}
