apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-microservice
  name: payments-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-microservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-microservice
    spec:
      containers:
      - image: 586250440358.dkr.ecr.us-east-1.amazonaws.com/payments-microservice
        name: payments-microservice
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: STRIPE_SUCCESS_URL
          value: "http://localhost:3003/payments/success"
        - name: STRIPE_CANCEL_URL
          value: "http://localhost:3003/payments/cancel"
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_secret_key
        - name: STRIPE_ENDPOINT_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_endpoint_secret
        - name: STRIPE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_public_key
        resources: {}
status: {}
