apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-webhook
  name: payments-webhook
spec:
  ports:
  - name: "3004"
    port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: payments-microservice
  type: NodePort
status:
  loadBalancer: {}
